version: "3"
services:
  site:
    command: jekyll serve --config _config.yml,_config_dev.yml
    image: jekyll/jekyll:latest
    container_name: "${PROJECT_NAME}_conviviojekyll"
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    labels:
      - 'traefik.backend=site'
      - 'traefik.port=4000'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
      - 'traefik.docker.network=traefik'
    networks:
      - traefik

  # portainer:
  #   image: portainer/portainer
  #   container_name: "${PROJECT_NAME}_portainer"
  #   command: --no-auth -H unix:///var/run/docker.sock
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   labels:
  #     - 'traefik.backend=portainer'
  #     - 'traefik.port=9000'
  #     - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  # traefik:
  #   image: traefik
  #   container_name: "${PROJECT_NAME}_traefik"
  #   command: -c /dev/null --web --docker --logLevel=INFO
  #   ports:
  #     - '80:80'
  #     # - '8080:8080' # Dashboard
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external: true
